import datetime
now=datetime.datetime.now()
dtm=str(now)
item=input("enetr the name of product")
price=int(input("Enter the price of product:"))
qty=int(input("Enter the Quantity of the product:00"))
val=price*qty
tax=val*0.05
net=val+tax
print("-"*65)
print("\t\t\tINVOICE")
print("-"*65)
print()
print("Dtae:{0:>55s}".format(dtm))
print()
print("item\t\t\tUnit Priice \tQuantity\tValue")
print("-"*65)
print("{0:<25s}".format(item),end='')
print("{0:>7.2f}".format(price),end='')
print("{0:>10d}".format(qty),end='')
print("{0:>14.2f}".format(val))
print()
print("TAx:{0:>57.2f}".format(tax))
print("-"*65)
print("Amount Payable:{0:>46.2f}".format(net))
